name: vpn_client
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.12+12

environment:
  sdk: ^3.7.2
  flutter: 3.29.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_svg: ^2.0.17
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_native_splash: ^2.3.1
  flutter_bloc: ^9.0.0
  vpnclient_engine_flutter:
    git:
      url: https://github.com/VPNclient/VPNclient-engine-flutter.git
      ref: c3bf79010c05a2474a24f763d428a61788a13e9b
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_code_metrics: ^4.19.2
  flutter_gen: ^5.3.0

flutter:
  generate: true  # ✅ ESSENCIAL para gerar flutter_gen и l10n корректно
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/flags/

flutter_gen:
  output: lib/gen/  # ✅ Define где генерировать файлы

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  untranslated-messages-file: lib/l10n/untranslated_messages.txt
